from datetime import datetime
now = datetime.now ()
year = now.strftime ("%Y")
print("year:", year)
month = now.strftime ("%m")
print("month:", month)
print("*"*30)
day = now.strftime("%d")
print("day:",day)
time=now.strftime("%H:%M:%S")
print("time:",time)
date_time=now.strftime("%m/%d/%Y, %H:%M:%S")
print("Date and Time:",date_time)